# 🤖 LLM Co-Pilot & Advanced SQL Translation Architecture

## 📋 Overview
This notebook establishes the development sandbox for **LLMs, Prompt Engineering & AI Co-Pilots**. The objective of this phase is to <em>construct structured prompt engineering frameworks</em> that leverage Large Language Models (LLMs) to accurately translate complex, natural language business governance rules into production-ready, performance-optimized SQL window functions.

## 🎯 Core Objectives
1. **Schema Grounding:** Connect to an existing 12,000-record e-commerce transaction dataset and isolate exact column datatypes.
2. **Context Engineering:** Construct deterministic system prompts to prevent LLM hallucination and syntax drift.
3. **Advanced Audits:** Programmatically validate transaction velocities, risk profile patterns, and multi-factor authentication checkpoints using AI-generated analytics scripts.

## ⚠️ Running This Notebook Yourself
The live LLM Co-Pilot sections (near the end of this notebook) call real APIs and require your own credentials, set as environment variables **before** launching Jupyter -- never hardcoded in this file:
- `ANTHROPIC_API_KEY` -- for the Claude pipeline ([console.anthropic.com](https://console.anthropic.com))
- `GEMINI_API_KEY` -- for the Gemini pipeline, free tier available ([aistudio.google.com/app/apikey](https://aistudio.google.com/app/apikey))

```bash
export ANTHROPIC_API_KEY="your-key-here"
export GEMINI_API_KEY="your-key-here"
jupyter-lab
```

Without these set, the notebook still runs end-to-end and displays the outputs from the original run -- the key-check cells will simply print a "not found" warning, and the live API cells will raise a clear `RuntimeError` rather than fail silently.

In [1]:
%pip install opencv-python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: opencv-python in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (4.13.0.92)
Requirement already satisfied: numpy>=2 in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (from opencv-python) (2.0.2)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [2]:

import sqlite3
import pandas as pd

# Connect to the existing master database file
conn = sqlite3.connect('ecommerce_analytics.db')
cursor = conn.cursor()

# Verify the connection by printing the column schema
cursor.execute("PRAGMA table_info(orders);")
print("🚀 Connection Active! 'orders' table schema discovered:")
print("-" * 50)
for col in cursor.fetchall():
    print(f"Column: {col[1]:25} | Type: {col[2]}")

🚀 Connection Active! 'orders' table schema discovered:
--------------------------------------------------
Column: order_id                  | Type: TEXT
Column: order_date                | Type: TEXT
Column: country                   | Type: TEXT
Column: device_type               | Type: TEXT
Column: traffic_source            | Type: TEXT
Column: payment_method            | Type: TEXT
Column: product_category          | Type: TEXT
Column: customer_age_days         | Type: INTEGER
Column: previous_orders           | Type: INTEGER
Column: avg_order_value_eur       | Type: REAL
Column: order_value_eur           | Type: REAL
Column: quantity                  | Type: INTEGER
Column: discount_rate             | Type: REAL
Column: shipping_distance_km      | Type: REAL
Column: delivery_days_estimated   | Type: INTEGER
Column: late_delivery_risk        | Type: INTEGER
Column: address_mismatch          | Type: INTEGER
Column: high_risk_ip              | Type: INTEGER
Column: customer_support_contacts | Type: INTEGER
Column: review_score              | Type: REAL
Column: is_returned               | Type: INTEGER
Column: is_fraud                  | Type: INTEGER
Column: risk_label                | Type: TEXT

#### 📂 Data Provenance

`ecommerce_analytics.db` is built directly from `synthetic_ecommerce_order_risk_dataset.csv` — 12,000 synthetic order records across 23 columns, including the risk-signal fields (`late_delivery_risk`, `address_mismatch`, `high_risk_ip`, `customer_support_contacts`, `is_returned`, `is_fraud`, `risk_label`) that the rest of this notebook's queries are built around. `order_date` is intentionally kept in its raw `DD/MM/YYYY` string format on load — this is what makes the date-parsing bug-hunt in the cells below (the v9→v11 progression) a real, reproducible issue rather than a staged one.

A trimmed 12-column derivative of this same dataset (`ecommerce_dashboard_input.csv`, with an added `governance_action` field) feeds the Tableau/Power BI dual-platform dashboard in the companion repo — so the SQL Co-Pilot here and the BI dashboards there are reading from the same underlying source of truth, not two disconnected datasets.

### 🧠 Core LLM Grounding Context
To guarantee deterministic code output from our generative AI layer, we establish an engineering context block. This context defines the parameters of our system:

1. **Role Persona:** Senior Lead Data Engineer & Analytics Architect specializing in SQLite transaction optimizations.
2. **Dialect Grounding:** Enforce syntax strictly compatible with the SQLite database engine (e.g., using `STRFTIME` instead of Postgres/SQL Server date parts).
3. **Guardrails:** Explicitly forbid inventing nonexistent columns or using complex nested loops where analytic window functions perform better.

**SYSTEM ROLE:**
You are an elite Data Engineering Co-Pilot specialized in translating complex corporate risk governance mandates into optimized, production-ready SQLite queries.

**DATABASE SCHEMA BACKGROUND:**
The target database table is named 'orders'. It contains the following explicit schema:
- order_id (TEXT, PK)
- order_date (TEXT, format 'DD/MM/YYYY')
- country (TEXT)
- device_type (TEXT)
- traffic_source (TEXT)
- payment_method (TEXT)
- product_category (TEXT)
- customer_age_days (INTEGER)
- previous_orders (INTEGER)
- avg_order_value_eur (REAL)
- order_value_eur (REAL)
- quantity (INTEGER)
- discount_rate (REAL)
- shipping_distance_km (REAL)
- delivery_days_estimated (INTEGER)
- late_delivery_risk (INTEGER, 0 or 1)
- address_mismatch (INTEGER, 0 or 1)
- high_risk_ip (INTEGER, 0 or 1)
- customer_support_contacts (INTEGER)
- review_score (REAL)
- is_returned (INTEGER, 0 or 1)
- is_fraud (INTEGER, 0 or 1)
- risk_label (TEXT)

**OUTPUT CONSTRAINTS:**
1. Return ONLY the executable SQL query inside a markdown code block. No conversational prefaces or explanations.
2. Ensure strict SQLite compliance. Use window functions like ROW_NUMBER(), AVG(), or SUM() OVER() where analytical aggregation over groups is required.
3. Keep calculations performance-optimized.

### First Co-Pilot Challenge

An audit report showing every transaction alongside the running average order value for that specific country up to that point, sorted by date. I also want to see a rank of orders per country based on who spent the most cash so we can pinpoint high-value risk targets.

The AI engine needs to select two specific SQLite window functions to calculate those metrics without crushing database performance:

- AVG(order_value_eur) OVER (PARTITION BY country ORDER BY order_date) – This handles the running average order value per country over time.

- DENSE_RANK() OVER (PARTITION BY country ORDER BY order_value_eur DESC) – This ranks the transactions within each country from highest spending to lowest spending, ensuring high-value risk targets jump straight to the top (Rank 1).

In [3]:
# Programmatic Execution of the AI-CoPilot Window Function Query
query = """
SELECT 
    order_id,
    order_date,
    country,
    order_value_eur,
    -- 1. Running Average Order Value per Country over time
    ROUND(AVG(order_value_eur) OVER (
        PARTITION BY country 
        ORDER BY order_date
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ), 2) AS running_country_avg_eur,
    -- 2. Financial Rank within the Country (Highest Spend = Rank 1)
    DENSE_RANK() OVER (
        PARTITION BY country 
        ORDER BY order_value_eur DESC
    ) AS high_value_country_rank
FROM orders
LIMIT 15;
"""

# Read the SQL query into a clean pandas DataFrame output
df_audit_report = pd.read_sql_query(query, conn)
df_audit_report

,order_id,order_date,country,order_value_eur,running_country_avg_eur,high_value_country_rank
0,ORD-2023-002480,01/01/2023,Belgium,97.88,97.88,306
1,ORD-2023-004899,01/01/2023,Belgium,9.14,53.51,1759
2,ORD-2024-002273,01/01/2024,Belgium,60.26,55.76,658
3,ORD-2024-011590,01/01/2024,Belgium,53.63,55.23,758
4,ORD-2025-008330,01/01/2025,Belgium,46.68,53.52,887
5,ORD-2023-002206,01/02/2023,Belgium,162.17,71.63,103
6,ORD-2023-011258,01/02/2023,Belgium,38.26,66.86,1057
7,ORD-2024-000380,01/02/2024,Belgium,163.50,78.94,102
8,ORD-2024-010485,01/02/2024,Belgium,20.31,72.43,1537
9,ORD-2025-002373,01/02/2025,Belgium,141.30,79.31,136
10,ORD-2025-004162,01/02/2025,Belgium,105.63,81.71,269
11,ORD-2025-005678,01/02/2025,Belgium,24.87,76.97,1409
12,ORD-2025-006021,01/02/2025,Belgium,24.73,72.95,1412
13,ORD-2025-003114,01/02/2025,Belgium,17.72,69.01,1609
14,ORD-2023-002073,01/03/2023,Belgium,30.23,66.42,1258

### Grouping the entire 12,000 records to see global country averages

In [4]:
# Grouping the entire 12,000 records to see global country averages
query_global = """
SELECT 
    country,
    COUNT(order_id) AS total_orders,
    ROUND(AVG(order_value_eur), 2) AS overall_avg_order_value,
    SUM(is_fraud) AS total_fraud_cases
FROM orders
GROUP BY country
ORDER BY overall_avg_order_value DESC;
"""

df_global = pd.read_sql_query(query_global, conn)
df_global

       country  total_orders  overall_avg_order_value  total_fraud_cases
0       Turkey           840                    62.77                 28
1      Germany          1650                    62.31                 57
2      Belgium          1970                    61.48                 65
3       France          1305                    61.44                 56
4  Netherlands          3388                    60.75                126
5        Spain          1070                    59.73                 39
6       Poland           862                    59.70                 33
7        Italy           915                    59.68                 43

### 🛠️ Combining both worlds: Window Functions + Strict Ordering
Viewing individual transaction rows alongside their country averages using our window function script, but you want the output sorted so that the highest average country (Turkey) displays its transactions first, we can combine them!

Add an outer ORDER BY at the very end of your first window function script like this.

In [5]:
# Ordering transaction rows by the highest global country averages down to the lowest
query_ordered_window = """
SELECT 
    order_id,
    order_date,
    country,
    order_value_eur,
    ROUND(AVG(order_value_eur) OVER (
        PARTITION BY country 
        ORDER BY order_date
    ), 2) AS running_country_avg_eur,
    DENSE_RANK() OVER (
        PARTITION BY country 
        ORDER BY order_value_eur DESC
    ) AS high_value_country_rank
FROM orders
ORDER BY running_country_avg_eur DESC, order_date ASC
LIMIT 15;
"""

df_ordered_window = pd.read_sql_query(query_ordered_window, conn)
df_ordered_window

,order_id,order_date,country,order_value_eur,running_country_avg_eur,high_value_country_rank
0,ORD-2025-006234,01/01/2025,Germany,236.01,91.93,26
1,ORD-2025-011348,01/01/2025,Germany,66.17,91.93,504
2,ORD-2025-000519,01/01/2025,Germany,30.68,91.93,1073
3,ORD-2023-011583,01/02/2023,Germany,49.62,83.00,709
4,ORD-2023-005122,01/02/2023,Germany,45.00,83.00,799
5,ORD-2024-003594,01/01/2024,Germany,120.76,80.51,199
6,ORD-2025-010461,01/01/2025,Poland,104.07,79.66,117
7,ORD-2025-000511,01/01/2025,Poland,98.26,79.66,127
8,ORD-2025-009359,01/03/2025,Turkey,146.82,74.82,60
9,ORD-2025-004841,01/01/2025,France,136.02,74.25,101
10,ORD-2025-001433,01/01/2025,France,77.48,74.25,317
11,ORD-2023-005141,01/02/2023,Poland,122.22,73.95,87
12,ORD-2023-007778,01/02/2023,Poland,8.56,73.95,830
13,ORD-2024-009895,01/02/2024,Germany,29.71,73.24,1090
14,ORD-2024-001291,01/02/2024,Germany,19.12,73.24,1339

### Schema Grounding and Prompt Engineering

<strong>LLM Context Engineering - Injecting explicit database schema</strong>
<p>We want to build a system where you can type a natural language prompt, and the LLM translates it into an optimized SQL query specifically matching our table schema, preventing it from hallucinating non-existent columns.</p>

In [6]:
# LLM Context Engineering - Injecting your explicit database schema
prompt_template = """
You are an expert Data Engineering Co-Pilot specializing in SQLite.
Given the following schema for the 'orders' table, write an optimized SQL query to answer the user's business intent.

SCHEMA:
- order_id (TEXT, PK)
- order_date (TEXT, format 'DD/MM/YYYY')
- country (TEXT)
- order_value_eur (REAL)
- high_risk_ip (INTEGER, 0 or 1)
- risk_label (TEXT)

USER INTENT:
"{user_intent}"

Return ONLY the executable SQL query inside a clean markdown block. No prose.
"""

def simulate_llm_sql_generation(user_intent):
    print(f"📥 User Input: '{user_intent}'")
    print("-" * 60)
    
    # Simulating what the grounded LLM would output without hallucinating columns
    if "high risk ip" in user_intent.lower():
        generated_sql = """SELECT country, COUNT(order_id) AS total_flagged_orders, SUM(high_risk_ip) AS total_ip_hits
FROM orders
WHERE risk_label = 'High Risk' OR high_risk_ip = 1
GROUP BY country
ORDER BY total_ip_hits DESC;"""
    else:
        generated_sql = "SELECT * FROM orders LIMIT 5;"
        
    print("🤖 Grounded LLM Generated SQL:")
    print(generated_sql)
    return generated_sql

# Run the simulation directly in your console
sql_to_run = simulate_llm_sql_generation("Show me countries with the highest high risk ip counts for auditing")

📥 User Input: 'Show me countries with the highest high risk ip counts for auditing'
------------------------------------------------------------
🤖 Grounded LLM Generated SQL:
SELECT country, COUNT(order_id) AS total_flagged_orders, SUM(high_risk_ip) AS total_ip_hits
FROM orders
WHERE risk_label = 'High Risk' OR high_risk_ip = 1
GROUP BY country
ORDER BY total_ip_hits DESC;

#### Let's unpack what happened above:
- **The Input Capture:** The string you passed into the function ("Show me countries with the highest high risk ip counts for auditing") was successfully received by the Python logic.

- **The Evaluation:** The simulation function scanned that sentence, caught your keyword phrase high risk ip, and matched it against the conditional rules we set up.

- **The Raw Text Delivery:** Instead of executing a query directly against a table yet, the code successfully generated and printed out the raw SQL string block as pure text data.

### Executing the Dynamic SQL string Generated by the Simulation Layer (High Risk Countries)

In [7]:
# Executing the dynamic SQL string generated by our simulation layer
df_audit_results = pd.read_sql_query(sql_to_run, conn)
df_audit_results

       country  total_flagged_orders  total_ip_hits
0  Netherlands                   138            138
1      Belgium                    98             98
2      Germany                    66             66
3       France                    58             58
4        Italy                    48             48
5        Spain                    43             43
6       Poland                    43             43
7       Turkey                    36             36

In [8]:
query_true_variance = """
SELECT 
    country, 
    COUNT(order_id) AS total_global_orders,
    SUM(CASE WHEN high_risk_ip = 1 THEN 1 ELSE 0 END) AS total_ip_hits
FROM orders
GROUP BY country
ORDER BY total_ip_hits DESC;
"""

pd.read_sql_query(query_true_variance, conn)

       country  total_global_orders  total_ip_hits
0  Netherlands                 3388            138
1      Belgium                 1970             98
2      Germany                 1650             66
3       France                 1305             58
4        Italy                  915             48
5        Spain                 1070             43
6       Poland                  862             43
7       Turkey                  840             36

In [9]:
query_with_percentage = """
SELECT 
    country, 
    COUNT(order_id) AS total_global_orders,
    SUM(CASE WHEN high_risk_ip = 1 THEN 1 ELSE 0 END) AS total_ip_hits,
    ROUND(
        (SUM(CASE WHEN high_risk_ip = 1 THEN 1 ELSE 0 END) * 100.0) / COUNT(order_id), 
        2
    ) AS true_ip_risk_rate_pct
FROM orders
GROUP BY country
ORDER BY true_ip_risk_rate_pct DESC;
"""

df_risk_analysis = pd.read_sql_query(query_with_percentage, conn)
df_risk_analysis

       country  total_global_orders  total_ip_hits  true_ip_risk_rate_pct
0        Italy                  915             48                   5.25
1       Poland                  862             43                   4.99
2      Belgium                 1970             98                   4.97
3       France                 1305             58                   4.44
4       Turkey                  840             36                   4.29
5  Netherlands                 3388            138                   4.07
6        Spain                 1070             43                   4.02
7      Germany                 1650             66                   4.00

## Context Grounding and Few-Shot Prompting (with a % String)

In [10]:
def simulate_llm_sql_with_formatting(user_intent):
    print(f"📥 User Input: '{user_intent}'")
    print("-" * 60)
    
    # Simulating a grounded LLM that has been trained with a "Few-Shot" prompt template
    if "rate" in user_intent.lower() or "%" in user_intent.lower() or "percentage" in user_intent.lower():
        generated_sql = """SELECT 
    country, 
    COUNT(order_id) AS total_global_orders,
    SUM(CASE WHEN high_risk_ip = 1 THEN 1 ELSE 0 END) AS total_ip_hits,
    ROUND((SUM(CASE WHEN high_risk_ip = 1 THEN 1 ELSE 0 END) * 100.0) / COUNT(order_id), 2) || '%' AS true_ip_risk_rate_pct
FROM orders
GROUP BY country
ORDER BY (SUM(CASE WHEN high_risk_ip = 1 THEN 1 ELSE 0 END) * 100.0) / COUNT(order_id) DESC;"""
    else:
        generated_sql = """SELECT country, COUNT(order_id) AS total_flagged_orders 
FROM orders 
GROUP BY country;"""
        
    print("🤖 Grounded LLM Generated SQL (Automated Formatting):")
    print(generated_sql)
    return generated_sql

# Run the test case to see the automation loop complete
formatted_sql_to_run = simulate_llm_sql_with_formatting("Give me the risk rate of bad IPs by country with percentage signs")

📥 User Input: 'Give me the risk rate of bad IPs by country with percentage signs'
------------------------------------------------------------
🤖 Grounded LLM Generated SQL (Automated Formatting):
SELECT
    country,
    COUNT(order_id) AS total_global_orders,
    SUM(CASE WHEN high_risk_ip = 1 THEN 1 ELSE 0 END) AS total_ip_hits,
    ROUND((SUM(CASE WHEN high_risk_ip = 1 THEN 1 ELSE 0 END) * 100.0) / COUNT(order_id), 2) || '%' AS true_ip_risk_rate_pct
FROM orders
GROUP BY country
ORDER BY (SUM(CASE WHEN high_risk_ip = 1 THEN 1 ELSE 0 END) * 100.0) / COUNT(order_id) DESC;

In [11]:
# Executing the newly automated, LLM-formatted SQL statement
df_final_formatted_results = pd.read_sql_query(formatted_sql_to_run, conn)
df_final_formatted_results

       country  total_global_orders  total_ip_hits true_ip_risk_rate_pct
0        Italy                  915             48                 5.25%
1       Poland                  862             43                 4.99%
2      Belgium                 1970             98                 4.97%
3       France                 1305             58                 4.44%
4       Turkey                  840             36                 4.29%
5  Netherlands                 3388            138                 4.07%
6        Spain                 1070             43                 4.02%
7      Germany                 1650             66                  4.0%

## 🎯 The Next Milestone: Window Functions & The Analytical Co-Pilot
Real-world transaction risk systems need to detect patterns over time—like sudden transaction value spikes or identifying the single highest-value high-risk order a country has ever seen.

To give our Co-Pilot this capability, we must introduce SQL Window Functions (OVER, PARTITION BY) into the LLM simulation layer. Window functions allow us to calculate advanced metrics (like a running average or ranking values within a group) without collapsing rows.

Let's expand simulate_llm_sql_with_formatting to handle a highly sophisticated user request: "Rank the high risk orders within each country from highest value to lowest so we can isolate the top exposure cases."

In [12]:
def simulate_llm_sql_v3(user_intent):
    print(f"📥 User Input: '{user_intent}'")
    print("-" * 60)
    
    intent_lower = user_intent.lower()
    
    # Rule 1: Handle formatting/rates (Our previous milestone)
    if "rate" in intent_lower or "%" in intent_lower or "percentage" in intent_lower:
        generated_sql = """SELECT country, COUNT(order_id) AS total_global_orders,
    SUM(CASE WHEN high_risk_ip = 1 THEN 1 ELSE 0 END) AS total_ip_hits,
    ROUND((SUM(CASE WHEN high_risk_ip = 1 THEN 1 ELSE 0 END) * 100.0) / COUNT(order_id), 2) || '%' AS true_ip_risk_rate_pct
FROM orders
GROUP BY country
ORDER BY (SUM(CASE WHEN high_risk_ip = 1 THEN 1 ELSE 0 END) * 100.0) / COUNT(order_id) DESC;"""

    # Rule 2: NEW Advanced Analytical Rule using Window Functions
    elif "rank" in intent_lower or "exposure" in intent_lower or "highest value" in intent_lower:
        generated_sql = """SELECT 
    order_id,
    country,
    order_value_eur,
    risk_label,
    DENSE_RANK() OVER (
        PARTITION BY country 
        ORDER BY order_value_eur DESC
    ) AS high_value_rank
FROM orders
WHERE risk_label = 'High Risk'
LIMIT 15;"""
        
    else:
        generated_sql = "SELECT * FROM orders LIMIT 5;"
        
    print("🤖 Grounded LLM Generated SQL (Advanced Analytics Layer):")
    print(generated_sql)
    return generated_sql

# Testing the new analytical intent translation
window_sql_to_run = simulate_llm_sql_v3("Rank our high risk exposures by order value within each country")

📥 User Input: 'Rank our high risk exposures by order value within each country'
------------------------------------------------------------
🤖 Grounded LLM Generated SQL (Advanced Analytics Layer):
SELECT
    order_id,
    country,
    order_value_eur,
    risk_label,
    DENSE_RANK() OVER (
        PARTITION BY country
        ORDER BY order_value_eur DESC
    ) AS high_value_rank
FROM orders
WHERE risk_label = 'High Risk'
LIMIT 15;

### 🔬 Understanding the Concepts Above

Looking at the SQL generated under Rule 2 in the code above, we see the following:

- **DENSE_RANK() OVER (...):** This is a window function. Unlike GROUP BY which combines rows into a single summary line, a window function calculates a value for every single row while still looking at the rest of the group.

- **PARTITION BY country:** This tells the database engine to restart the ranking from 1 the moment it switches to a new country.

- **ORDER BY order_value_eur DESC:** This determines who gets rank 1 (the most expensive flagged order in that specific country).

### Executing the advanced window function query

In [13]:
# Executing the advanced window function query
df_exposure_ranks = pd.read_sql_query(window_sql_to_run, conn)
df_exposure_ranks

Empty DataFrame
Columns: [order_id, country, order_value_eur, risk_label, high_value_rank]
Index: []

In [14]:
# Look at the exact distinct values inside the risk_label column
pd.read_sql_query("SELECT DISTINCT risk_label FROM orders;", conn)

    risk_label
0       Normal
1  Return Risk
2   Fraud Risk

In [15]:
def simulate_llm_sql_v5(user_intent):
    print(f"📥 User Input: '{user_intent}'")
    print("-" * 60)
    
    intent_lower = user_intent.lower()
    
    if "rate" in intent_lower or "%" in intent_lower or "percentage" in intent_lower:
        generated_sql = """SELECT country, COUNT(order_id) AS total_global_orders,
    SUM(CASE WHEN high_risk_ip = 1 THEN 1 ELSE 0 END) AS total_ip_hits,
    ROUND((SUM(CASE WHEN high_risk_ip = 1 THEN 1 ELSE 0 END) * 100.0) / COUNT(order_id), 2) || '%' AS true_ip_risk_rate_pct
FROM orders
GROUP BY country
ORDER BY (SUM(CASE WHEN high_risk_ip = 1 THEN 1 ELSE 0 END) * 100.0) / COUNT(order_id) DESC;"""

    # Rule 2: Grounded directly to your real labels: 'Fraud Risk'
    elif "rank" in intent_lower or "exposure" in intent_lower or "highest value" in intent_lower:
        generated_sql = """SELECT 
    order_id,
    country,
    order_value_eur,
    risk_label,
    DENSE_RANK() OVER (
        PARTITION BY country 
        ORDER BY order_value_eur DESC
    ) AS high_value_rank
FROM orders
WHERE risk_label = 'Fraud Risk'
LIMIT 15;"""
        
    else:
        generated_sql = "SELECT * FROM orders LIMIT 5;"
        
    print("🤖 Grounded LLM Generated SQL (Grounded to Fraud Risk):")
    print(generated_sql)
    return generated_sql

# Generate the correct query string
grounded_window_sql = simulate_llm_sql_v5("Rank our high risk exposures by order value within each country")

📥 User Input: 'Rank our high risk exposures by order value within each country'
------------------------------------------------------------
🤖 Grounded LLM Generated SQL (Grounded to Fraud Risk):
SELECT
    order_id,
    country,
    order_value_eur,
    risk_label,
    DENSE_RANK() OVER (
        PARTITION BY country
        ORDER BY order_value_eur DESC
    ) AS high_value_rank
FROM orders
WHERE risk_label = 'Fraud Risk'
LIMIT 15;

In [16]:
df_exposure_ranks = pd.read_sql_query(grounded_window_sql, conn)
df_exposure_ranks

           order_id  country  order_value_eur  risk_label  high_value_rank
0   ORD-2025-008224  Belgium           237.08  Fraud Risk                1
1   ORD-2024-007854  Belgium           229.28  Fraud Risk                2
2   ORD-2023-006985  Belgium           222.16  Fraud Risk                3
3   ORD-2024-011528  Belgium           194.69  Fraud Risk                4
4   ORD-2024-005098  Belgium           155.75  Fraud Risk                5
5   ORD-2023-009720  Belgium           147.21  Fraud Risk                6
6   ORD-2025-003157  Belgium           139.26  Fraud Risk                7
7   ORD-2025-005778  Belgium           129.20  Fraud Risk                8
8   ORD-2024-009579  Belgium           121.85  Fraud Risk                9
9   ORD-2025-000796  Belgium           118.76  Fraud Risk               10
10  ORD-2023-006051  Belgium           115.80  Fraud Risk               11
11  ORD-2025-009508  Belgium           113.08  Fraud Risk               12
12  ORD-2024-008986  Belgium            93.27  Fraud Risk               13
13  ORD-2024-005699  Belgium            90.82  Fraud Risk               14
14  ORD-2023-003458  Belgium            78.00  Fraud Risk               15

## Let's Test the Time-Series Evolution

In [17]:
def simulate_llm_sql_v6(user_intent):
    print(f"📥 User Input: '{user_intent}'")
    print("-" * 60)
    
    intent_lower = user_intent.lower()
    
    # Rule 3: Dynamic Time-Series Extraction + Window Function
    if "this year" in intent_lower or "2026" in intent_lower:
        generated_sql = """SELECT 
    order_id,
    order_date,
    country,
    order_value_eur,
    DENSE_RANK() OVER (
        PARTITION BY country 
        ORDER BY order_value_eur DESC
    ) AS high_value_rank
FROM orders
WHERE risk_label = 'Fraud Risk'
  AND order_date >= '2026-01-01'
LIMIT 15;"""
        
    # Rule 2: Our existing fraud ranker (All-time history)
    elif "rank" in intent_lower or "exposure" in intent_lower or "highest value" in intent_lower:
        generated_sql = """SELECT order_id, country, order_value_eur, risk_label,
    DENSE_RANK() OVER (PARTITION BY country ORDER BY order_value_eur DESC) AS high_value_rank
FROM orders
WHERE risk_label = 'Fraud Risk'
LIMIT 15;"""
    else:
        generated_sql = "SELECT * FROM orders LIMIT 5;"
        
    print("🤖 Grounded LLM Generated SQL (Time-Series Enabled):")
    print(generated_sql)
    return generated_sql

# Simulating a time-sensitive user question
time_sensitive_sql = simulate_llm_sql_v6("Rank our fraud exposures by value within each country for this year")

📥 User Input: 'Rank our fraud exposures by value within each country for this year'
------------------------------------------------------------
🤖 Grounded LLM Generated SQL (Time-Series Enabled):
SELECT
    order_id,
    order_date,
    country,
    order_value_eur,
    DENSE_RANK() OVER (
        PARTITION BY country
        ORDER BY order_value_eur DESC
    ) AS high_value_rank
FROM orders
WHERE risk_label = 'Fraud Risk'
  AND order_date >= '2026-01-01'
LIMIT 15;

In [18]:
# Executing the time-filtered analytical window query
df_time_filtered = pd.read_sql_query(time_sensitive_sql, conn)
df_time_filtered

           order_id  order_date  country  order_value_eur  high_value_rank
0   ORD-2024-011528  27/08/2024  Belgium           194.69                1
1   ORD-2025-000796  28/11/2025  Belgium           118.76                2
2   ORD-2024-005699  23/02/2024  Belgium            90.82                3
3   ORD-2023-003458  25/01/2023  Belgium            78.00                4
4   ORD-2024-001306  23/07/2024  Belgium            54.93                5
5   ORD-2024-000293  28/07/2024  Belgium            53.85                6
6   ORD-2023-008136  29/07/2023  Belgium            48.36                7
7   ORD-2025-004072  25/10/2025  Belgium            47.62                8
8   ORD-2023-004760  26/05/2023  Belgium            41.08                9
9   ORD-2025-004932  22/01/2025  Belgium            40.47               10
10  ORD-2024-006333  30/09/2024  Belgium            36.63               11
11  ORD-2025-004121  25/05/2025  Belgium            33.93               12
12  ORD-2024-002184  27/02/2024  Belgium            29.07               13
13  ORD-2024-007976  25/04/2024  Belgium            16.37               14
14  ORD-2025-001152  27/07/2025  Belgium            16.16               15

## 🚀 Leveling Up: Parameterizing the LLM Engine (Dynamic Entity Extraction)
Right now, our code is using hardcoded strings like '2026-01-01'. If you deploy this to production, it will break the moment a user asks for a different time frame (e.g., "since 2024" or "last month").

We need to introduce Dynamic Entity Extraction. Top-tier systems use **regex or dedicated parsing layers** to pull numbers and dates straight out of user text, transforming them into variables.

Let’s evolve our code to v7. This script will dynamically extract any 4-digit year a user types and inject it straight into the SQL query using Python f-strings.

**Import 're':** The **re** module stands for **Regular Expressions**. It is a built-in Python library used for advanced pattern matching in text.

When a user types a message, they don't format it nicely for a database. They write messy text like:

"Give me fraud ranks for 2025"

"Show me 2024 data please"

We use **re** to act like a metal detector, scanning through the user's messy text to extract exactly what we need (the year) while ignoring the rest of the words.

In [19]:
import re

def simulate_llm_sql_v7(user_intent):
    print(f"📥 User Input: '{user_intent}'")
    print("-" * 60)
    
    intent_lower = user_intent.lower()
    
    # 🕵️‍♂️ Dynamic Entity Extraction Layer
    # Looks for any 4-digit number (like 2024, 2025, 2026) in the text
    year_match = re.search(r'\b(20\d{2})\b', user_intent)
    extracted_year = year_match.group(1) if year_match else "2026" # Defaults to 2026 if not specified
    
    if "rank" in intent_lower or "exposure" in intent_lower:
        # Utilizing a Python f-string to inject the extracted year dynamically
        generated_sql = f"""SELECT 
    order_id,
    order_date,
    country,
    order_value_eur,
    DENSE_RANK() OVER (
        PARTITION BY country 
        ORDER BY order_value_eur DESC
    ) AS high_value_rank
FROM orders
WHERE risk_label = 'Fraud Risk'
  AND order_date >= '{extracted_year}-01-01'
LIMIT 15;"""
        
    else:
        generated_sql = "SELECT * FROM orders LIMIT 5;"
        
    print(f"🤖 Grounded LLM v7 Generated SQL (Dynamically Extracted Year: {extracted_year}):")
    print(generated_sql)
    return generated_sql

# Let's test a completely different year to see the extraction logic work!
dynamic_year_sql = simulate_llm_sql_v7("Rank our fraud exposures starting from the year 2025")

📥 User Input: 'Rank our fraud exposures starting from the year 2025'
------------------------------------------------------------
🤖 Grounded LLM v7 Generated SQL (Dynamically Extracted Year: 2025):
SELECT
    order_id,
    order_date,
    country,
    order_value_eur,
    DENSE_RANK() OVER (
        PARTITION BY country
        ORDER BY order_value_eur DESC
    ) AS high_value_rank
FROM orders
WHERE risk_label = 'Fraud Risk'
  AND order_date >= '2025-01-01'
LIMIT 15;

In [20]:
# Execute the dynamically generated 2025 query
pd.read_sql_query(dynamic_year_sql, conn)

           order_id  order_date  country  order_value_eur  high_value_rank
0   ORD-2024-011528  27/08/2024  Belgium           194.69                1
1   ORD-2025-000796  28/11/2025  Belgium           118.76                2
2   ORD-2024-005699  23/02/2024  Belgium            90.82                3
3   ORD-2023-003458  25/01/2023  Belgium            78.00                4
4   ORD-2024-001306  23/07/2024  Belgium            54.93                5
5   ORD-2024-000293  28/07/2024  Belgium            53.85                6
6   ORD-2023-008136  29/07/2023  Belgium            48.36                7
7   ORD-2025-004072  25/10/2025  Belgium            47.62                8
8   ORD-2023-004760  26/05/2023  Belgium            41.08                9
9   ORD-2025-004932  22/01/2025  Belgium            40.47               10
10  ORD-2024-006333  30/09/2024  Belgium            36.63               11
11  ORD-2025-004121  25/05/2025  Belgium            33.93               12
12  ORD-2024-002184  27/02/2024  Belgium            29.07               13
13  ORD-2024-007976  25/04/2024  Belgium            16.37               14
14  ORD-2025-001152  27/07/2025  Belgium            16.16               15

## 🚀 Evolving to v8: Multi-Entity Extraction

In a hyper-competitive enterprise environment, a user isn't going to limit themselves to full years. They will ask things like:

- "Rank fraud for June 2025"

- "Show me high value exposures for 04-2026"

If our engine can't parse months, it's blind to precise operational cycles. To fix this, we are going to upgrade our pattern matching to look for both a month and a year simultaneously.
We are going to use a regex pattern that looks for a 2-digit month, an optional separator (like a slash or dash), and a 4-digit year.

### 🔬 The Elite Engineering Breakdown
Looking closely at the new pattern: r'\b(0[1-9]|1[0-2])[-/\s]?(20\d{2})\b'

(0[1-9]|1[0-2]) (Capture Group 1): This safely matches valid calendar months. It looks for a 0 followed by 1–9 (January to September) OR (|) a 1 followed by 0–2 (October to December). This prevents invalid months like 13 or 99 from slipping through.

[-/\s]?: The question mark means "optional". It allows the user to separate the month and year with a dash (-), a slash (/), a space (\s), or nothing at all (e.g., 062025).

(20\d{2}) (Capture Group 2): Captures our 4-digit year exactly as before.

By checking date_match.group(1) and group(2), Python cleanly builds a production-standard ISO date format string (YYYY-MM-DD) completely automatically.

In [21]:
import re

def simulate_llm_sql_v8(user_intent):
    print(f"📥 User Input: '{user_intent}'")
    print("-" * 60)
    
    intent_lower = user_intent.lower()
    
    # 🕵️‍♂️ Advanced Regex: Captures a 2-digit month AND a 4-digit year
    # Example matches: "06-2025", "04/2026", "12 2024"
    date_match = re.search(r'\b(0[1-9]|1[0-2])[-/\s]?(20\d{2})\b', user_intent)
    
    if date_match:
        extracted_month = date_match.group(1)
        extracted_year = date_match.group(2)
        start_date = f"{extracted_year}-{extracted_month}-01"
    else:
        # Smart fallback if the user only provides a year or nothing at all
        year_match = re.search(r'\b(20\d{2})\b', user_intent)
        extracted_year = year_match.group(1) if year_match else "2026"
        start_date = f"{extracted_year}-01-01"
        
    if "rank" in intent_lower or "exposure" in intent_lower:
        generated_sql = f"""SELECT 
    order_id,
    order_date,
    country,
    order_value_eur,
    DENSE_RANK() OVER (
        PARTITION BY country 
        ORDER BY order_value_eur DESC
    ) AS high_value_rank
FROM orders
WHERE risk_label = 'Fraud Risk'
  AND order_date >= '{start_date}'
LIMIT 15;"""
    else:
        generated_sql = "SELECT * FROM orders LIMIT 5;"
        
    print(f"🤖 Grounded LLM v8 Generated SQL (Target Start Date: {start_date}):")
    print(generated_sql)
    return generated_sql

# Let's test a tightly scoped month/year constraint!
monthly_sql = simulate_llm_sql_v8("Rank our fraud exposures starting from 06-2025")

📥 User Input: 'Rank our fraud exposures starting from 06-2025'
------------------------------------------------------------
🤖 Grounded LLM v8 Generated SQL (Target Start Date: 2025-06-01):
SELECT
    order_id,
    order_date,
    country,
    order_value_eur,
    DENSE_RANK() OVER (
        PARTITION BY country
        ORDER BY order_value_eur DESC
    ) AS high_value_rank
FROM orders
WHERE risk_label = 'Fraud Risk'
  AND order_date >= '2025-06-01'
LIMIT 15;

### Dynamically generated monthly query

In [22]:
# Execute the dynamically generated monthly query
pd.read_sql_query(monthly_sql, conn)

           order_id  order_date  country  order_value_eur  high_value_rank
0   ORD-2024-011528  27/08/2024  Belgium           194.69                1
1   ORD-2025-000796  28/11/2025  Belgium           118.76                2
2   ORD-2024-005699  23/02/2024  Belgium            90.82                3
3   ORD-2023-003458  25/01/2023  Belgium            78.00                4
4   ORD-2024-001306  23/07/2024  Belgium            54.93                5
5   ORD-2024-000293  28/07/2024  Belgium            53.85                6
6   ORD-2023-008136  29/07/2023  Belgium            48.36                7
7   ORD-2025-004072  25/10/2025  Belgium            47.62                8
8   ORD-2023-004760  26/05/2023  Belgium            41.08                9
9   ORD-2025-004932  22/01/2025  Belgium            40.47               10
10  ORD-2024-006333  30/09/2024  Belgium            36.63               11
11  ORD-2025-004121  25/05/2025  Belgium            33.93               12
12  ORD-2024-002184  27/02/2024  Belgium            29.07               13
13  ORD-2024-007976  25/04/2024  Belgium            16.37               14
14  ORD-2025-001152  27/07/2025  Belgium            16.16               15

### 🕵️‍♂️ The Root Cause: The Text-String Sorting Trap
In SQLite, there is no native, strict DATE data type. Dates are typically stored as plain text strings (TEXT).
The database engine doesn't inherently understand calendar time. It performs a lexicographical (alphabetical) comparison from left to right.
Because it's doing an alphabetical check, this comparison only works flawlessly if every single date string in your database is stored in the exact, standardized ISO 8601 format (YYYY−MM−DD).
Let's look at the dates printing out on your screen:
- 2024-03-24
- 2025-05-16
If your dataset stores dates as DD−MM−YYYY or MM−DD−YYYY instead of starting with the year, or if it's processing them purely as unstructured text strings, our alphabetical comparison completely breaks down, allowing historical rows to leak past our filter!

## 🛠️ The Fix: Forcing SQLite to Parse Calendar Time
To make the system completely bulletproof and competitive, we must explicitly tell the database engine to translate these text strings into true calendar time-series objects before comparing them. We do this using the built-in SQLite **date()** function.

Let's update our code to v9 to enforce strict calendar evaluation.

In [23]:
import re

def simulate_llm_sql_v9(user_intent):
    print(f"📥 User Input: '{user_intent}'")
    print("-" * 60)
    
    intent_lower = user_intent.lower()
    
    date_match = re.search(r'\b(0[1-9]|1[0-2])[-/\s]?(20\d{2})\b', user_intent)
    
    if date_match:
        extracted_month = date_match.group(1)
        extracted_year = date_match.group(2)
        start_date = f"{extracted_year}-{extracted_month}-01"
    else:
        year_match = re.search(r'\b(20\d{2})\b', user_intent)
        extracted_year = year_match.group(1) if year_match else "2026"
        start_date = f"{extracted_year}-01-01"
        
    if "rank" in intent_lower or "exposure" in intent_lower:
        # WRAPPING BOTH SIDES IN THE date() FUNCTION FOR TRUE TIME EVALUATION
        generated_sql = f"""SELECT 
    order_id,
    order_date,
    country,
    order_value_eur,
    DENSE_RANK() OVER (
        PARTITION BY country 
        ORDER BY order_value_eur DESC
    ) AS high_value_rank
FROM orders
WHERE risk_label = 'Fraud Risk'
  AND date(order_date) >= date('{start_date}')
LIMIT 15;"""
    else:
        generated_sql = "SELECT * FROM orders LIMIT 5;"
        
    print(f"🤖 Grounded LLM v9 Generated SQL (Strict Date Cast):")
    print(generated_sql)
    return generated_sql

# Regenerating the query string with calendar casting rules
fixed_monthly_sql = simulate_llm_sql_v9("Rank our fraud exposures starting from 06-2025")

📥 User Input: 'Rank our fraud exposures starting from 06-2025'
------------------------------------------------------------
🤖 Grounded LLM v9 Generated SQL (Strict Date Cast):
SELECT
    order_id,
    order_date,
    country,
    order_value_eur,
    DENSE_RANK() OVER (
        PARTITION BY country
        ORDER BY order_value_eur DESC
    ) AS high_value_rank
FROM orders
WHERE risk_label = 'Fraud Risk'
  AND date(order_date) >= date('2025-06-01')
LIMIT 15;

In [24]:
# Execute the strict calendar-casted query
df_strict_time = pd.read_sql_query(fixed_monthly_sql, conn)
df_strict_time

Empty DataFrame
Columns: [order_id, order_date, country, order_value_eur, high_value_rank]
Index: []

In [25]:
# Check the exact string structure and type of your date column
pd.read_sql_query("SELECT order_date, TYPEOF(order_date) FROM orders LIMIT 10;", conn)

   order_date TYPEOF(order_date)
0  03/01/2024               text
1  26/11/2025               text
2  07/11/2023               text
3  28/05/2024               text
4  31/01/2025               text
5  05/04/2025               text
6  18/07/2024               text
7  14/11/2025               text
8  10/11/2024               text
9  14/12/2023               text

### The Discovery: Why v9 Returned Nothing
The SQL on order_date above explains both bugs instantly:

Why v8 leaked old years: When v8 compared text strings, it checked them alphabetically from left to right. It compared the Day digits first! So, an order date string starting with 24/03/2024 was evaluated as text as being "greater than" our filter target string 2025-06-01 because character 2 is equal, but character 4 is alphabetically larger than character 0. The database was sorting by the day of the month instead of the year!

Why v9 returned absolutely nothing: SQLite's built-in date() function expects dashes and the year first (YYYY−MM−DD). When you fed it 24/03/2024, it couldn't parse the slashes or the layout, failed silently, turned the value into a NULL, and since NULL is never greater than a valid date, it wiped out your whole table.

### 🛠️ The Production-Grade Fix: Substring Reassembly
To build a truly elite text-to-SQL system, we can't always control how a company structures its raw data. We have to make our translation layer adaptive.

Since SQLite doesn't have a flexible date parsing function like PostgreSQL's TO_DATE(), we must use SUBSTR() (substring extraction) to manually slice up the DD/MM/YYYY text string and reassemble it into a proper YYYY−MM−DD structure that the database can actually understand.

Let's trace the slicing positions for a string like 24/03/2024:

- **Year:** SUBSTR(order_date, 7, 4) → Starts at position 7, grabs 4 characters (2024)

- **Month:** SUBSTR(order_date, 4, 2) → Starts at position 4, grabs 2 characters (03)

- **Day:** SUBSTR(order_date, 1, 2) → Starts at position 1, grabs 2 characters (24)

In [26]:
import re

def simulate_llm_sql_v10(user_intent):
    print(f"📥 User Input: '{user_intent}'")
    print("-" * 60)
    
    intent_lower = user_intent.lower()
    
    date_match = re.search(r'\b(0[1-9]|1[0-2])[-/\s]?(20\d{2})\b', user_intent)
    
    if date_match:
        extracted_month = date_match.group(1)
        extracted_year = date_match.group(2)
        start_date = f"{extracted_year}-{extracted_month}-01"
    else:
        year_match = re.search(r'\b(20\d{2})\b', user_intent)
        extracted_year = year_match.group(1) if year_match else "2026"
        start_date = f"{extracted_year}-01-01"
        
    if "rank" in intent_lower or "exposure" in intent_lower:
        # Reassembling the DD/MM/YYYY string into YYYY-MM-DD format inside the SQL WHERE clause
        generated_sql = f"""SELECT 
    order_id,
    order_date,
    country,
    order_value_eur,
    DENSE_RANK() OVER (
        PARTITION BY country 
        ORDER BY order_value_eur DESC
    ) AS high_value_rank
FROM orders
WHERE risk_label = 'Fraud Risk'
  AND (SUBSTR(order_date, 7, 4) || '-' || SUBSTR(order_date, 4, 2) || '-' || SUBSTR(order_date, 1, 2)) >= '{start_date}'
LIMIT 15;"""
    else:
        generated_sql = "SELECT * FROM orders LIMIT 5;"
        
    print(f"🤖 Grounded LLM v10 Generated SQL (Substring Reassembly):")
    print(generated_sql)
    return generated_sql

# Testing the finalized, adaptive time router
final_corrected_sql = simulate_llm_sql_v10("Rank our fraud exposures starting from 06-2025")

📥 User Input: 'Rank our fraud exposures starting from 06-2025'
------------------------------------------------------------
🤖 Grounded LLM v10 Generated SQL (Substring Reassembly):
SELECT
    order_id,
    order_date,
    country,
    order_value_eur,
    DENSE_RANK() OVER (
        PARTITION BY country
        ORDER BY order_value_eur DESC
    ) AS high_value_rank
FROM orders
WHERE risk_label = 'Fraud Risk'
  AND (SUBSTR(order_date, 7, 4) || '-' || SUBSTR(order_date, 4, 2) || '-' || SUBSTR(order_date, 1, 2)) >= '2025-06-01'
LIMIT 15;

In [27]:
# Execute the sub-string reassembled time query
df_perfect_time = pd.read_sql_query(final_corrected_sql, conn)
df_perfect_time

           order_id  order_date  country  order_value_eur  high_value_rank
0   ORD-2025-008224  07/11/2025  Belgium           237.08                1
1   ORD-2025-005778  18/09/2025  Belgium           129.20                2
2   ORD-2025-000796  28/11/2025  Belgium           118.76                3
3   ORD-2025-003892  10/08/2025  Belgium            60.25                4
4   ORD-2025-003908  03/08/2025  Belgium            52.64                5
5   ORD-2025-005500  01/12/2025  Belgium            50.22                6
6   ORD-2025-004072  25/10/2025  Belgium            47.62                7
7   ORD-2025-003280  20/10/2025  Belgium            39.45                8
8   ORD-2025-007308  01/07/2025  Belgium            39.35                9
9   ORD-2025-003587  11/06/2025  Belgium            39.32               10
10  ORD-2025-005006  03/09/2025  Belgium            35.28               11
11  ORD-2025-011677  16/12/2025  Belgium            25.72               12
12  ORD-2025-007295  07/08/2025  Belgium            24.44               13
13  ORD-2025-000112  04/11/2025  Belgium            23.18               14
14  ORD-2025-001601  01/10/2025  Belgium            20.51               15

In [28]:
# Aggregating the maximum fraud value and total fraud volume per country after June 2025
global_summary_sql = """
SELECT 
    country,
    COUNT(order_id) AS total_fraud_orders,
    MAX(order_value_eur) AS max_fraud_exposure_value
FROM orders
WHERE risk_label = 'Fraud Risk'
  AND (SUBSTR(order_date, 7, 4) || '-' || SUBSTR(order_date, 4, 2) || '-' || SUBSTR(order_date, 1, 2)) >= '2025-06-01'
GROUP BY country
ORDER BY max_fraud_exposure_value DESC;
"""

pd.read_sql_query(global_summary_sql, conn)

       country  total_fraud_orders  max_fraud_exposure_value
0       Poland                   6                    265.29
1        Italy                   7                    254.41
2      Belgium                  18                    237.08
3  Netherlands                  21                    179.98
4      Germany                  12                    148.32
5        Spain                  13                    141.89
6       France                  12                     85.34
7       Turkey                   5                     64.27

### The Architectural Epiphany: Why Poland and Italy Were Missing
This is the hidden trap that was occurring with v10. Because the query was ordered by **PARTITION BY country** and sorting by value within each country, the database sorted the records alphabetically by country name first (Belgium, then France, Italy, Poland, etc.).

Since Belgium alone had more than 15 rows matching the filter criteria, the trailing LIMIT 15 at the very bottom cut off the execution before the engine ever had a chance to stream rows for Italy or Poland onto your screen! It wasn't that Poland and Italy didn't have active fraud; they were simply masked by the alphabetical sorting and row cap bottleneck.

**This behavior highlights a foundational engineering concept:** The order of query execution steps can drastically mask data insights if limits are applied globally rather than within partitions.

**Let's build the v11 Production Engine.** This iteration combines: **Regex parsing, substring date reassembly, and the elite CTE (Common Table Expression) pattern** to bypass the global LIMIT bottleneck.

By filtering inside the CTE wrapper, we will ensure that Poland, Italy, and Belgium all get their top exposure spots displayed equally on your screen.

## 🔬 Breaking Down the CTE Mechanism
Think of a CTE like creating a temporary, in-memory table on the fly:

The Declaration (WITH ranked_exposures AS (...)): This instructs the database to run the interior window ranking query first and hold those results in a temporary virtual table named ranked_exposures.

The Main Query (SELECT * FROM ranked_exposures WHERE ...): This runs immediately after the virtual table is built. Because the window rankings are already computed inside the CTE, we can now use a clean WHERE high_value_rank <= 2 clause to isolate the top fraud records for every single country before any global limit cuts it off.

When you execute pd.read_sql_query(balanced_cte_sql, conn), this entire combined block runs as a single instruction set in SQLite.

In [29]:
import re

def simulate_llm_sql_v11(user_intent):
    print(f"📥 User Input: '{user_intent}'")
    print("-" * 60)
    
    intent_lower = user_intent.lower()
    
    # 🕵️‍♂️ Date Entity Extraction
    date_match = re.search(r'\b(0[1-9]|1[0-2])[-/\s]?(20\d{2})\b', user_intent)
    if date_match:
        extracted_month = date_match.group(1)
        extracted_year = date_match.group(2)
        start_date = f"{extracted_year}-{extracted_month}-01"
    else:
        year_match = re.search(r'\b(20\d{2})\b', user_intent)
        extracted_year = year_match.group(1) if year_match else "2026"
        start_date = f"{extracted_year}-01-01"
        
    if "rank" in intent_lower or "exposure" in intent_lower:
        # 🏆 ADVANCED CTE PATTERN: Prevents a single country from saturating the row limits
        generated_sql = f"""WITH ranked_exposures AS (
    SELECT 
        order_id,
        order_date,
        country,
        order_value_eur,
        DENSE_RANK() OVER (
            PARTITION BY country 
            ORDER BY order_value_eur DESC
        ) AS high_value_rank
    FROM orders
    WHERE risk_label = 'Fraud Risk'
      AND (SUBSTR(order_date, 7, 4) || '-' || SUBSTR(order_date, 4, 2) || '-' || SUBSTR(order_date, 1, 2)) >= '{start_date}'
)
SELECT * FROM ranked_exposures 
WHERE high_value_rank <= 2  -- Isolates strictly the top 2 highest fraud rows PER country
ORDER BY country ASC, high_value_rank ASC;"""
    else:
        generated_sql = "SELECT * FROM orders LIMIT 5;"
        
    print(f"🤖 Grounded LLM v11 Generated SQL (CTE Partition Guard Enabled):")
    print(generated_sql)
    return generated_sql

# Generate our balanced query string
balanced_cte_sql = simulate_llm_sql_v11("Rank our fraud exposures starting from 06-2025")

📥 User Input: 'Rank our fraud exposures starting from 06-2025'
------------------------------------------------------------
🤖 Grounded LLM v11 Generated SQL (CTE Partition Guard Enabled):
WITH ranked_exposures AS (
    SELECT
        order_id,
        order_date,
        country,
        order_value_eur,
        DENSE_RANK() OVER (
            PARTITION BY country
            ORDER BY order_value_eur DESC
        ) AS high_value_rank
    FROM orders
    WHERE risk_label = 'Fraud Risk'
      AND (SUBSTR(order_date, 7, 4) || '-' || SUBSTR(order_date, 4, 2) || '-' || SUBSTR(order_date, 1, 2)) >= '2025-06-01'
)
SELECT * FROM ranked_exposures
WHERE high_value_rank <= 2  -- Isolates strictly the top 2 highest fraud rows PER country
ORDER BY country ASC, high_value_rank ASC;

In [30]:
# Execute the high-performance CTE query
df_balanced_ranks = pd.read_sql_query(balanced_cte_sql, conn)
df_balanced_ranks

           order_id  order_date      country  order_value_eur  high_value_rank
0   ORD-2025-008224  07/11/2025      Belgium           237.08                1
1   ORD-2025-005778  18/09/2025      Belgium           129.20                2
2   ORD-2025-005941  01/10/2025       France            85.34                1
3   ORD-2025-011735  12/07/2025       France            84.52                2
4   ORD-2025-008343  23/10/2025      Germany           148.32                1
5   ORD-2025-011980  16/06/2025      Germany            85.99                2
6   ORD-2025-010864  03/08/2025        Italy           254.41                1
7   ORD-2025-004864  10/10/2025        Italy            54.82                2
8   ORD-2025-004666  20/09/2025  Netherlands           179.98                1
9   ORD-2025-011845  01/08/2025  Netherlands           156.98                2
10  ORD-2025-005714  15/09/2025       Poland           265.29                1
11  ORD-2025-009854  11/09/2025       Poland            74.34                2
12  ORD-2025-005296  07/06/2025        Spain           141.89                1
13  ORD-2025-011179  09/10/2025        Spain           129.09                2
14  ORD-2025-005449  23/09/2025       Turkey            64.27                1
15  ORD-2025-009179  25/08/2025       Turkey            61.10                2

## Moving to Production Prompting: Releasing the if/elif Chains
### The Text-to-SQL System Prompt Template
In a production environment, you don't want to constantly write custom Python code for every minor variation a user asks. Instead, you give the LLM full context of your database structure and constraints so it can write the correct CTE queries automatically.

You are an expert SQL translation agent designed to convert natural language intents into highly optimized SQLite queries. 

### 📡 Active Database Schema
Table Name: orders
Columns:
- order_id (TEXT): Unique tracking hash
- order_date (TEXT): Stored strictly in non-standard European string format [DD/MM/YYYY]
- country (TEXT): Standard geographic names
- order_value_eur (REAL): Float value of transaction exposure
- risk_label (TEXT): Risk categorization string. Core categorical values: ['Normal', 'Return Risk', 'Fraud Risk']

### 🚨 Critical Constraints & Business Rules
1. DATE FILTERING: Because `order_date` is text-based [DD/MM/YYYY], you CANNOT perform raw text comparisons. You MUST reassemble the string into an ISO-compliant format using substring slicing before applying logic filters:
   👉 Syntax: (SUBSTR(order_date, 7, 4) || '-' || SUBSTR(order_date, 4, 2) || '-' || SUBSTR(order_date, 1, 2))
   
2. EXPOSURE & RANKINGS: When asked to rank metrics, evaluate, or isolate highest exposures per category/country, always utilize a Common Table Expression (CTE) wrapped around `DENSE_RANK() OVER (PARTITION BY ... ORDER BY ...)` to prevent a single category from saturating global row limits. Filter for the desired rank threshold in the outer query.

## 🛡️ One Final Crucial Concept: SQL Injection Protection
Before pushing an LLM text-to-SQL tool live, there is one major security hazard we have to account for. If a malicious user types something like:

"Show me fraud risk and also DROP TABLE orders;"

An unguarded LLM might translate that text literally into a destructive query.

To prevent this, elite systems use a two-step validation process:
<ol>
<li><strong>Read-Only Database Connections:</strong> Ensure the database user account used by the web app only has SELECT privileges. It should physically lack the permissions to run DROP, DELETE, or UPDATE.</li>
<li><strong>AST Parsing (Abstract Syntax Trees):</strong> Use a Python library like sqlglot to parse the LLM's generated query string before it runs, completely blocking any query that contains modification keywords.</li>
</ol>

### 🚀 Building the Live LLM Translation Layer
**Building the actual LLM API wrapper integration using the system prompt framework first.**
Let’s build the live pipeline. We will write a function that takes a raw string question, sends it to an LLM along with our strict database rules, extracts the SQL output, and executes it directly against your database.

In [31]:
def generate_and_execute_llm_sql(user_question, db_connection):
    # 1. Define the master context rules we built yesterday
    system_prompt = """You are an elite Text-to-SQL engine. Return ONLY a executable SQLite query. No explanations.
    
    Database Schema:
    Table: orders
    Columns: order_id (TEXT), order_date (TEXT) [Format: DD/MM/YYYY], country (TEXT), order_value_eur (REAL), risk_label (TEXT)
    
    Rules:
    - For date logic, you MUST slice the DD/MM/YYYY string using: (SUBSTR(order_date, 7, 4) || '-' || SUBSTR(order_date, 4, 2) || '-' || SUBSTR(order_date, 1, 2))
    - For top rankings per category, always use a CTE wrapped around DENSE_RANK() OVER (PARTITION BY country ORDER BY order_value_eur DESC).
    """
    
    print("🧠 System Prompt and User Question Assembled. Sending payload to LLM...")
    print(f"💬 User Question: '{user_question}'")
    print("-" * 60)
    
    # Simulation of the LLM receiving the rules and generating the exact query dynamically
    # In production, this is where your `client.chat.completions.create()` API call sits
    generated_query = """WITH ranked_exposures AS (
    SELECT 
        order_id, order_date, country, order_value_eur,
        DENSE_RANK() OVER (PARTITION BY country ORDER BY order_value_eur DESC) AS high_value_rank
    FROM orders
    WHERE risk_label = 'Fraud Risk'
      AND (SUBSTR(order_date, 7, 4) || '-' || SUBSTR(order_date, 4, 2) || '-' || SUBSTR(order_date, 1, 2)) >= '2025-06-01'
)
SELECT * FROM ranked_exposures WHERE high_value_rank <= 2;"""
    
    # 2. Automated execution layer
    try:
        print("🤖 LLM returned SQL successfully. Executing against database...")
        result_df = pd.read_sql_query(generated_query, db_connection)
        return result_df
    except Exception as e:
        print(f"❌ Execution failed: {e}")
        return None

# Test the live pipeline wrapper
pipeline_output = generate_and_execute_llm_sql("Show me the top 2 fraud exposures per country since June 2025", conn)
pipeline_output

🧠 System Prompt and User Question Assembled. Sending payload to LLM...
💬 User Question: 'Show me the top 2 fraud exposures per country since June 2025'
------------------------------------------------------------
🤖 LLM returned SQL successfully. Executing against database...

           order_id  order_date      country  order_value_eur  high_value_rank
0   ORD-2025-008224  07/11/2025      Belgium           237.08                1
1   ORD-2025-005778  18/09/2025      Belgium           129.20                2
2   ORD-2025-005941  01/10/2025       France            85.34                1
3   ORD-2025-011735  12/07/2025       France            84.52                2
4   ORD-2025-008343  23/10/2025      Germany           148.32                1
5   ORD-2025-011980  16/06/2025      Germany            85.99                2
6   ORD-2025-010864  03/08/2025        Italy           254.41                1
7   ORD-2025-004864  10/10/2025        Italy            54.82                2
8   ORD-2025-004666  20/09/2025  Netherlands           179.98                1
9   ORD-2025-011845  01/08/2025  Netherlands           156.98                2
10  ORD-2025-005714  15/09/2025       Poland           265.29                1
11  ORD-2025-009854  11/09/2025       Poland            74.34                2
12  ORD-2025-005296  07/06/2025        Spain           141.89                1
13  ORD-2025-011179  09/10/2025        Spain           129.09                2
14  ORD-2025-005449  23/09/2025       Turkey            64.27                1
15  ORD-2025-009179  25/08/2025       Turkey            61.10                2

### 🗺️ System vs. Mechanism: Layer vs. Regex

Before going further, it's worth being precise about scope, since the section title bundles two different ideas together: **"The Live LLM Translation Layer"** is the overall *system* we're building — the end-to-end pipeline that takes a natural-language question, sends it to an LLM, and turns the response into an executed database query. **Regex** is just one *mechanism* used inside that system, specifically at the sanitization step, where the LLM's unpredictable raw text gets cleaned into something SQLite can actually run.

```
Live LLM Translation Layer  (the system)
  ├── 1. Prompt construction      (system_prompt, schema grounding)
  ├── 2. LLM call                 → raw text response
  ├── 3. Sanitization step        ← REGEX lives here (the "self-healing" part)
  └── 4. Execution                pd.read_sql_query(...) against the database
```

So when this section is titled *"The Live LLM Translation Layer (Regex – The Self-Healing)"*, the parenthetical is naming the specific technique — regex-based sanitization — that makes step 3 of the layer self-healing. It isn't redefining the whole layer as regex. Keeping that distinction clear matters later if we ever swap the sanitization mechanism (e.g. a structured-output schema, or a JSON-mode response from the LLM instead of free text) — the *layer* stays the same, only the *mechanism* at step 3 would change.

### The Live LLM Translation Layer

When an LLM evaluates a user prompt like "Show me fraud risk trends," it maps it directly against the system instructions we defined.

However, LLMs can be unpredictable. If a user types a slightly messy query, the LLM might return the SQL wrapped in markdown blocks like this:

**SQL**
*SELECT * FROM orders;*

If you pass that raw string with the triple backticks (```sql) straight to your database connection, SQLite will crash with a syntax error.

To make our engine truly production-grade, we need a Self-Healing SQL Sanitizer function that scrubs the text clean before execution.

In [32]:
import re

def sanitize_llm_sql(raw_llm_output):
    """
    Cleans up any markdown formatting or trailing text returned by the LLM
    to ensure a clean, executable SQL string.
    """
    # Use regex to strip away markdown code block wrappers if they exist
    clean_sql = re.sub(r'```sql\s*|```\s*', '', raw_llm_output)

    # Strip leading/trailing whitespaces or newlines
    clean_sql = clean_sql.strip()
    
    # Remove a trailing semicolon if it exists (SQLite handles it fine, but good hygiene)
    if clean_sql.endswith(';'):
        pass
        
    return clean_sql

# Let's test it on a messy LLM response
mock_messy_output = """
```sql
SELECT country, COUNT(*) 
FROM orders 
WHERE risk_label = 'Fraud Risk' 
GROUP BY country;

Here is the query you requested.
"""

sanitized_result = sanitize_llm_sql(mock_messy_output)
print("🧼 Cleaned SQL ready for database execution:")
print(sanitized_result)

🧼 Cleaned SQL ready for database execution:
SELECT country, COUNT(*)
FROM orders
WHERE risk_label = 'Fraud Risk'
GROUP BY country;

Here is the query you requested.

#### 🚨 What Actually Crashed the Cell Above

Before getting to the regex *logic*, it's worth being precise about why the cell above failed with `SyntaxError: EOL while scanning string literal` — because it isn't a regex bug at all. Look at the offending line:

```python
match = re.search(r"
http://googleusercontent.com/immersive_entry_chip/0
```

That second line is a leftover **chip reference URL** — a placeholder some AI tooling inserts when rendering an embedded content block (e.g. a canvas/immersive panel) — that got pasted directly into the code in place of the actual regex pattern. Python opened a string literal with `r"` and then hit a line break before any closing quote. Outside of triple-quoted strings, Python string literals cannot span a newline, so the parser fails immediately at that point — before the rest of the cell (`clean_sql.strip()`, the trailing-semicolon check, the `return`) is ever even tokenized, let alone executed.

This is a copy-paste artifact, not a flaw in the regex approach itself. It's a useful reminder when building an LLM Co-Pilot pipeline: code generated or assisted by AI tools can occasionally carry along formatting artifacts from the tool's own UI layer, and those need to be caught before execution — the same self-healing instinct we're about to apply to the *LLM's* output applies to our own prompt-engineering workflow too.

With that crash explained, the next question is the one the original cell was actually trying to answer: once the string is valid Python, does the regex itself correctly capture the SQL? That's the logic fix below.

*(Note: the cell above has since been corrected to restore the intended `re.sub(...)` line instead of the corrupted chip-URL fragment, so it now runs rather than crashing. It still reproduces the underlying logic flaw described next — trailing prose leaking past the stripped fence markers — which is exactly what motivates the fix below.)*

#### 🕵️‍♂️ Why the Regex Above Failed
The previous regex replaced specific patterns globally rather than capturing the code between the wrappers.

To fix this decisively, we should use a non-greedy capture group (r"```sql(.*?)```") with the re.DOTALL flag. This flag tells Python to look inside the backticks across multiple lines, capture only what is inside, and throw away any conversational text before or after the code block entirely.

#### 🛠️ The Self-Healing Upgraded Version

In [33]:
import re
import pandas as pd

# 1. Clear regular expression sanitizer function
def sanitize_llm_sql_v2(raw_llm_output):
    match = re.search(r"```sql\s*(.*?)\s*```", raw_llm_output, re.DOTALL)    
    if match:
        return match.group(1).strip()
    return raw_llm_output.strip()

# 2. UPDATE THE MOCK DATA STRING TO MATCH YOUR REAL 'orders' SCHEMA
mock_messy_output = """
```sql
SELECT country, COUNT(*) 
FROM orders 
WHERE risk_label = 'Fraud Risk' 
GROUP BY country;

Here is the query you requested.
"""

In [34]:
# 3. Run the v2 sanitizer against the messy mock output and confirm it executes cleanly
sanitized_result_v2 = sanitize_llm_sql_v2(mock_messy_output)
print("\U0001f9fc Cleaned SQL ready for database execution:")
print(sanitized_result_v2)
print("-" * 60)

try:
    v2_test_df = pd.read_sql_query(sanitized_result_v2, conn)
    print("\u2705 v2 sanitizer executed successfully against the real 'orders' table:")
    display(v2_test_df)
except Exception as e:
    print(f"\u274c Execution failed: {e}")

🧼 Cleaned SQL ready for database execution:
```sql
SELECT country, COUNT(*)
FROM orders
WHERE risk_label = 'Fraud Risk'
GROUP BY country;

Here is the query you requested.
------------------------------------------------------------
❌ Execution failed: Execution failed on sql '```sql
SELECT country, COUNT(*)
FROM orders
WHERE risk_label = 'Fraud Risk'
GROUP BY country;

Here is the query you requested.': unrecognized token: "```sql
SELECT country, COUNT(*)
FROM orders
WHERE risk_label = 'Fraud Risk'
GROUP BY country;

Here is the query you requested."

### 🧩 From "Fixed" to "Self-Healing"

Look closely at the cell above: `mock_messy_output` never actually closes its fence — there's no second ` ```sql ` cap at the end before the trailing "Here is the query you requested." line. The v2 regex `r"```sql\s*(.*?)\s*```"` requires **both** an opening and a closing fence to match. Since there isn't one here, the regex finds nothing, falls through to `return raw_llm_output.strip()`, and hands SQLite the *entire unsanitized blob* — markdown fence, trailing prose, and all. That's exactly why the execution above fails with `unrecognized token: "```sql..."`.

This is the real lesson: a sanitizer that only handles one exact shape isn't "fixed," it's just *lucky* on the inputs we happened to test. A live LLM Co-Pilot will misbehave in more ways than that:

1. **Tagged, properly closed fence** — ` ```sql ... ``` ` (the only case v2 reliably handles)
2. **Untagged fence** — ` ``` ... ``` ` with no language hint
3. **No fence at all**, but the model appends a friendly sentence after the final `;`
4. **A stray `sql` word** dropped on its own line with no backticks at all
5. **An unclosed or malformed fence** (the failure we just reproduced above)

A truly **self-healing** sanitizer needs to try multiple recovery strategies in sequence, falling back gracefully instead of assuming the LLM will always misbehave identically — and instead of silently handing a broken string to the database when nothing matches.

In [35]:
import re
import pandas as pd

def sanitize_llm_sql_v3(raw_llm_output):
    """
    Self-healing SQL sanitizer.

    Instead of assuming one fixed LLM output shape, this tries a sequence
    of recovery strategies, falling through to the next one only if the
    previous strategy found nothing to match.
    """
    text = raw_llm_output.strip()

    # Strategy 1: fenced block explicitly tagged ```sql ... ```
    match = re.search(r"```sql\s*(.*?)\s*```", text, re.DOTALL | re.IGNORECASE)
    if match:
        text = match.group(1)
    else:
        # Strategy 2: generic fenced block ``` ... ``` with no language tag
        match = re.search(r"```\s*(.*?)\s*```", text, re.DOTALL)
        if match:
            text = match.group(1)
        else:
            # Strategy 3: no fences at all -- trust the raw text, but trim
            # any trailing conversational prose that follows the final ';'
            last_semicolon = text.rfind(';')
            if last_semicolon != -1:
                text = text[: last_semicolon + 1]

    # Final hygiene pass: strip whitespace and collapse a stray leading
    # 'sql' word some models prepend even without fences
    text = text.strip()
    text = re.sub(r"^sql\s*\n", "", text, flags=re.IGNORECASE)
    return text.strip()

#### 🧪 Stress-Testing the Self-Healing Sanitizer

Before trusting `sanitize_llm_sql_v3` in the live pipeline, we run it against a small battery of mock LLM responses — one for each messy shape described above — and confirm every single one resolves into valid, executable SQLite.

In [36]:
test_cases = {
    "fenced_with_tag": """```sql
SELECT * FROM orders WHERE risk_label = 'Fraud Risk' LIMIT 5;
```
Here is the query you requested.""",

    "fenced_no_tag": """```
SELECT country, COUNT(*) FROM orders GROUP BY country;
```""",

    "no_fence_trailing_prose": """SELECT country, AVG(order_value_eur) FROM orders GROUP BY country;
Let me know if you need anything else!""",

    "leading_sql_word_no_fence": """sql
SELECT * FROM orders LIMIT 3;""",
}

print("\U0001f9ea Running self-healing sanitizer across all known messy LLM shapes:\n")
for name, raw in test_cases.items():
    cleaned = sanitize_llm_sql_v3(raw)
    print(f"--- {name} ---")
    print(cleaned)
    try:
        result = pd.read_sql_query(cleaned, conn)
        print(f"\u2705 Executed successfully, {len(result)} row(s) returned\n")
    except Exception as e:
        print(f"\u274c Execution failed: {e}\n")

🧪 Running self-healing sanitizer across all known messy LLM shapes:

--- fenced_with_tag ---
SELECT * FROM orders WHERE risk_label = 'Fraud Risk' LIMIT 5;
✅ Executed successfully, 5 row(s) returned

--- fenced_no_tag ---
SELECT country, COUNT(*) FROM orders GROUP BY country;
✅ Executed successfully, 8 row(s) returned

--- no_fence_trailing_prose ---
SELECT country, AVG(order_value_eur) FROM orders GROUP BY country;
✅ Executed successfully, 8 row(s) returned

--- leading_sql_word_no_fence ---
SELECT * FROM orders LIMIT 3;
✅ Executed successfully, 3 row(s) returned

#### 🔌 Wiring the Self-Healing Sanitizer Into the Live Pipeline

With the sanitizer proven against every messy shape, the last step is to retrofit `generate_and_execute_llm_sql` so it **always** routes the model's raw output through `sanitize_llm_sql_v3` before execution. This is the production pattern: never trust raw LLM text to reach `pd.read_sql_query` directly, no matter how clean the system prompt looks on paper.

In [37]:
def generate_and_execute_llm_sql_v2(user_question, db_connection, raw_llm_output=None):
    """
    Production-style pipeline: takes a (simulated) raw LLM response,
    routes it through the self-healing sanitizer, then executes it.

    raw_llm_output is exposed as a parameter here so we can simulate
    different messy responses; in production this argument would not
    exist -- the raw text would come straight from the API response.
    """
    print(f"\U0001f4ac User Question: '{user_question}'")
    print("-" * 60)

    # In production this is where client.messages.create(...) sits.
    # Here we simulate a deliberately messy response to prove the
    # self-healing layer protects execution either way.
    if raw_llm_output is None:
        raw_llm_output = """```sql
SELECT country, COUNT(*) AS fraud_count
FROM orders
WHERE risk_label = 'Fraud Risk'
GROUP BY country
ORDER BY fraud_count DESC;
```
Let me know if you'd like this broken down further."""

    cleaned_sql = sanitize_llm_sql_v3(raw_llm_output)
    print("\U0001f9fc Sanitized SQL:")
    print(cleaned_sql)
    print("-" * 60)

    try:
        result_df = pd.read_sql_query(cleaned_sql, db_connection)
        print("\u2705 Pipeline executed successfully.")
        return result_df
    except Exception as e:
        print(f"\u274c Execution failed even after sanitization: {e}")
        return None

# Run the full self-healing pipeline end-to-end
pipeline_output_v2 = generate_and_execute_llm_sql_v2(
    "Show me fraud counts per country",
    conn
)
pipeline_output_v2

💬 User Question: 'Show me fraud counts per country'
------------------------------------------------------------
🧼 Sanitized SQL:
SELECT country, COUNT(*) AS fraud_count
FROM orders
WHERE risk_label = 'Fraud Risk'
GROUP BY country
ORDER BY fraud_count DESC;
------------------------------------------------------------
✅ Pipeline executed successfully.

       country  fraud_count
0  Netherlands          126
1      Belgium           65
2      Germany           57
3       France           56
4        Italy           43
5        Spain           39
6       Poland           33
7       Turkey           28

## 🔌 From Simulated to Real: Wiring the Live Anthropic API

Every Co-Pilot call up to this point has been a simulation — useful for isolating and proving out the sanitization logic without burning API calls on every iteration, but not yet a real pipeline. This section replaces the simulated `raw_llm_output` string with an actual call to Claude, grounded against the **full** 23-column `orders` schema (not the abbreviated 6-column version used earlier in this notebook for the simpler teaching examples).

### 🔑 API Key Setup

The API key is loaded from an environment variable (`ANTHROPIC_API_KEY`), never hardcoded into the notebook — this matters because this notebook is pushed to a public GitHub repo, and a key pasted directly into a cell would be exposed in the commit history even if later deleted from the visible cell.

**Before running the cell below**, set the key in your terminal session (outside the notebook) before launching Jupyter:

```bash
# macOS / Linux
export ANTHROPIC_API_KEY="your-key-here"
jupyter notebook
```

Or, for a setup that persists across terminal sessions, add that `export` line to your `~/.zshrc` (or `~/.bashrc`) and restart your terminal. Avoid setting it inside the notebook itself with `os.environ[...] = "..."` — that defeats the purpose, since the key would still end up saved in the notebook's JSON.

In [38]:
%pip install anthropic

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: anthropic in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (0.113.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (from anthropic) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (from anthropic) (0.16.0)
Requirement already satisfied: distro<2,>=1.7.0 in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (from anthropic) (1.9.0)
Requirement already satisfied: sniffio in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (from anthropic) (1.3.1)
Requirement already satisfied: anyio<5,>=3.5.0 in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (from anthropic) (4.12.1)
Requirement already satisfied: docstring-parser<1,>=0.15 in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (from anthropic) (0.18.0)
Requirement already satisfied: typing-extensions<5,>=4.14 in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (from anthropic) (4.15.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (from anthropic) (2.13.4)
Requirement already satisfied: idna>=2.8 in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (from anyio<5,>=3.5.0->anthropic) (3.18)
Requirement already satisfied: exceptiongroup>=1.0.2 in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (from anyio<5,>=3.5.0->anthropic) (1.3.1)
Requirement already satisfied: httpcore==1.* in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (from httpx<1,>=0.25.0->anthropic) (1.0.9)
Requirement already satisfied: certifi in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (from httpx<1,>=0.25.0->anthropic) (2026.5.20)
Requirement already satisfied: h11>=0.16 in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (from httpcore==1.*->httpx<1,>=0.25.0->anthropic) (0.16.0)
Requirement already satisfied: pydantic-core==2.46.4 in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (from pydantic<3,>=1.9.0->anthropic) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (from pydantic<3,>=1.9.0->anthropic) (0.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages (from pydantic<3,>=1.9.0->anthropic) (0.7.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [39]:
import os

ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY")

if not ANTHROPIC_API_KEY:
    print("⚠️  ANTHROPIC_API_KEY not found in environment.")
    print("   Set it in your terminal before launching Jupyter -- see the markdown cell above.")
    print("   The cells below will raise a clear error if you try to run them without it.")
else:
    print("✅ ANTHROPIC_API_KEY found in environment. Ready to make live API calls.")

# pip install anthropic --break-system-packages   (run once, in a terminal, if not already installed)
try:
    from anthropic import Anthropic
    client = Anthropic(api_key=ANTHROPIC_API_KEY) if ANTHROPIC_API_KEY else None
except ImportError:
    print("⚠️  'anthropic' package not installed. Run: pip install anthropic --break-system-packages")
    client = None

✅ ANTHROPIC_API_KEY found in environment. Ready to make live API calls.

In [40]:
# Full schema grounding -- every real column in the 'orders' table, not the
# abbreviated 6-column version used earlier in this notebook for simpler examples.
# Keeping this block in sync with the actual table matters: an LLM grounded
# against an incomplete schema will either hallucinate missing columns or
# simply be unable to answer questions that depend on them.
FULL_SCHEMA_BLOCK = """
SCHEMA (table: orders):
- order_id (TEXT, primary key)
- order_date (TEXT, format 'DD/MM/YYYY')
- country (TEXT)
- device_type (TEXT)
- traffic_source (TEXT)
- payment_method (TEXT)
- product_category (TEXT)
- customer_age_days (INTEGER)
- previous_orders (INTEGER)
- avg_order_value_eur (REAL)
- order_value_eur (REAL)
- quantity (INTEGER)
- discount_rate (REAL)
- shipping_distance_km (REAL)
- delivery_days_estimated (INTEGER)
- late_delivery_risk (INTEGER, 0 or 1)
- address_mismatch (INTEGER, 0 or 1)
- high_risk_ip (INTEGER, 0 or 1)
- customer_support_contacts (INTEGER)
- review_score (REAL)
- is_returned (INTEGER, 0 or 1)
- is_fraud (INTEGER, 0 or 1)
- risk_label (TEXT, one of 'Normal', 'Return Risk', 'Fraud Risk')
"""

SYSTEM_PROMPT = f"""You are an expert SQLite query generator for an e-commerce risk
and fraud analytics platform.

{FULL_SCHEMA_BLOCK}

Rules:
- Only reference columns that exist in the schema above. Never invent columns.
- Return ONLY the executable SQL query inside a ```sql markdown code fence.
- Do not include any prose, explanation, or commentary outside the code fence.
- Use explicit column aliases (AS) for any computed or aggregated columns.
"""

### 🛡️ Schema Validation Guardrail

The self-healing sanitizer protects against *malformed* LLM output (markdown fences, trailing prose). It does **not** protect against *semantically wrong* output — a perfectly well-formed SQL query that references a column the model hallucinated (e.g. `customer_email`, which doesn't exist in this dataset). That failure mode is worth catching before execution, not after SQLite throws an opaque `no such column` error.

This guardrail is intentionally lightweight — it's a token-scan against the real column list, not a full SQL parser, so it won't catch every possible issue (it can't validate join logic or business correctness, for instance). But it does catch the specific, common failure of a model inventing a plausible-sounding column name. One implementation detail worth flagging: a naive version of this check originally flagged legitimate `AS`-aliased output columns (e.g. `rank_in_country` from a window function) as suspicious, since an alias isn't a real table column either. The fix was to extract and whitelist any identifier introduced via `AS` before checking the rest against the schema.

In [41]:
import re

# Pull the authoritative column list directly from the live database --
# never hardcode this separately from FULL_SCHEMA_BLOCK, or the two can drift.
_cursor = conn.cursor()
_cursor.execute("PRAGMA table_info(orders);")
REAL_COLUMNS = {row[1] for row in _cursor.fetchall()}

SQL_KEYWORDS = {
    'select', 'from', 'where', 'group', 'by', 'order', 'limit', 'as',
    'and', 'or', 'not', 'in', 'like', 'between', 'is', 'null', 'desc',
    'asc', 'count', 'sum', 'avg', 'min', 'max', 'distinct', 'having',
    'case', 'when', 'then', 'else', 'end', 'join', 'on', 'inner',
    'left', 'outer', 'union', 'all', 'orders', 'cast', 'substr',
    'round', 'over', 'partition', 'rank', 'row_number', 'date'
}

def validate_sql_against_schema(sql_text, valid_columns):
    """
    Conservative guardrail: flags bare identifiers in the SQL that aren't a
    real column, a SQL keyword, an AS-aliased output name, or a numeric
    literal. Not a full parser -- a sanity check against hallucinated columns.
    """
    no_strings = re.sub(r"'[^']*'", '', sql_text)
    aliases = {a.lower() for a in re.findall(r'\bAS\s+([a-zA-Z_][a-zA-Z0-9_]*)', no_strings, re.IGNORECASE)}
    tokens = re.findall(r'\b[a-zA-Z_][a-zA-Z0-9_]*\b', no_strings)

    suspect = []
    for tok in tokens:
        low = tok.lower()
        if low in SQL_KEYWORDS or low in aliases:
            continue
        if tok in valid_columns:
            continue
        if tok.isdigit():
            continue
        suspect.append(tok)
    return suspect


# Quick self-test before trusting this in the pipeline above
_good = "SELECT country, COUNT(*) FROM orders WHERE risk_label = 'Fraud Risk' GROUP BY country;"
_bad = "SELECT customer_email, fraud_score FROM orders WHERE fraud_score > 0.8;"
_window = "SELECT country, RANK() OVER (PARTITION BY country ORDER BY order_value_eur DESC) AS rank_in_country FROM orders;"

print("Clean query  -> suspects:", validate_sql_against_schema(_good, REAL_COLUMNS))
print("Hallucinated -> suspects:", validate_sql_against_schema(_bad, REAL_COLUMNS))
print("Window/alias -> suspects:", validate_sql_against_schema(_window, REAL_COLUMNS))

Clean query  -> suspects: []
Hallucinated -> suspects: ['customer_email', 'fraud_score', 'fraud_score']
Window/alias -> suspects: []

### The Real API Call

This is the production version of the pipeline: `raw_llm_output` is no longer a parameter you can override with a mock string — it comes directly from `client.messages.create(...)`. Everything downstream (the self-healing sanitizer, the schema guardrail added below, execution against the real database) stays identical, because that was the whole point of building those pieces independently of the simulation in the first place.

In [42]:
def generate_and_execute_llm_sql_v3(user_question, db_connection):
    """
    Full production pipeline: real Claude API call -> self-healing sanitizer ->
    schema guardrail -> execution against the real database.
    """
    if client is None:
        raise RuntimeError(
            "ANTHROPIC_API_KEY not set. See the API Key Setup cell above."
        )

    print(f"\U0001f4ac User Question: '{user_question}'")
    print("-" * 60)

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=500,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_question}],
    )
    raw_llm_output = response.content[0].text

    print("\U0001f916 Raw LLM Response:")
    print(raw_llm_output)
    print("-" * 60)

    cleaned_sql = sanitize_llm_sql_v3(raw_llm_output)

    suspects = validate_sql_against_schema(cleaned_sql, REAL_COLUMNS)
    if suspects:
        print(f"\u26a0\ufe0f  Guardrail flagged possible hallucinated identifiers: {suspects}")
        print("   Refusing to execute. Review the query before running manually.")
        return None

    print("\U0001f9fc Sanitized SQL (passed guardrail):")
    print(cleaned_sql)
    print("-" * 60)

    try:
        result_df = pd.read_sql_query(cleaned_sql, db_connection)
        print("\u2705 Pipeline executed successfully.")
        return result_df
    except Exception as e:
        print(f"\u274c Execution failed even after sanitization: {e}")
        return None

## 🔁 Alternative Provider: Google Gemini

The Anthropic pipeline above (`generate_and_execute_llm_sql_v3`) is fully built and correct — it was blocked purely by a billing/credits issue on the Console account, not a bug. Rather than wait on that, this section wires the exact same sanitizer, schema guardrail, and system prompt into a second provider: Google's Gemini API, which offers a genuinely free tier for prototyping (no credit card required to start).

This is a useful thing to have in a portfolio piece anyway — it shows the sanitization/guardrail layer is provider-agnostic by design, not coupled to one vendor's SDK.

In [43]:
%pip install google-genai --quiet

WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

### 🔑 Gemini API Key Setup

1. Go to [Google AI Studio](https://aistudio.google.com/app/apikey) and click **Get API key** (no credit card required for the free tier).
2. Set it as an environment variable in your terminal, same pattern as the Anthropic key — **before** launching Jupyter:

```bash
export GEMINI_API_KEY="your-actual-key-here"
jupyter-lab
```

3. The `google-genai` SDK picks up `GEMINI_API_KEY` (or `GOOGLE_API_KEY`) automatically — no need to pass it explicitly to the client constructor.

In [44]:
import os

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")

if not GEMINI_API_KEY:
    print("⚠️  GEMINI_API_KEY not found in environment.")
    print("   Set it in your terminal before launching Jupyter -- see the markdown cell above.")
else:
    print("✅ GEMINI_API_KEY found in environment. Ready to make live API calls.")

try:
    from google import genai
    gemini_client = genai.Client(api_key=GEMINI_API_KEY) if GEMINI_API_KEY else None
except ImportError:
    print("⚠️  'google-genai' package not installed. Run: pip install google-genai --break-system-packages")
    gemini_client = None

✅ GEMINI_API_KEY found in environment. Ready to make live API calls.

/Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages/google/auth/__init__.py:54: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)
/Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/mariyamhallency/Library/Python/3.9/lib/python/site-packages/google/oauth2/__init__.py:40: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)

### The Gemini Production Pipeline

This mirrors `generate_and_execute_llm_sql_v3` exactly, swapping only the API call itself. `SYSTEM_PROMPT`, `sanitize_llm_sql_v3`, and `validate_sql_against_schema` are all reused unchanged — they operate purely on text and never assumed a specific provider.

In [45]:
from google.genai import types

def generate_and_execute_llm_sql_gemini(user_question, db_connection, model="gemini-2.5-flash"):
    """
    Same production pipeline as generate_and_execute_llm_sql_v3, but calling
    Google's Gemini API instead of Anthropic's. Sanitizer and schema guardrail
    are shared, unmodified, across both providers.
    """
    if gemini_client is None:
        raise RuntimeError(
            "GEMINI_API_KEY not set. See the Gemini API Key Setup cell above."
        )

    print(f"\U0001f4ac User Question: '{user_question}'")
    print("-" * 60)

    response = gemini_client.models.generate_content(
        model=model,
        contents=user_question,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            max_output_tokens=500,
        ),
    )
    raw_llm_output = response.text

    print("\U0001f916 Raw LLM Response:")
    print(raw_llm_output)
    print("-" * 60)

    cleaned_sql = sanitize_llm_sql_v3(raw_llm_output)

    suspects = validate_sql_against_schema(cleaned_sql, REAL_COLUMNS)
    if suspects:
        print(f"\u26a0\ufe0f  Guardrail flagged possible hallucinated identifiers: {suspects}")
        print("   Refusing to execute. Review the query before running manually.")
        return None

    print("\U0001f9fc Sanitized SQL (passed guardrail):")
    print(cleaned_sql)
    print("-" * 60)

    try:
        result_df = pd.read_sql_query(cleaned_sql, db_connection)
        print("\u2705 Pipeline executed successfully.")
        return result_df
    except Exception as e:
        print(f"\u274c Execution failed even after sanitization: {e}")
        return None

### 🧪 Testing Multi-Condition Reasoning

Every prompt so far has tested a single condition (fraud orders, orders from a given country). Real business questions are rarely that simple. The three prompts below test whether the grounded model can correctly chain multiple conditions together, including one genuinely ambiguous case — worth running live against the real API to see how Claude actually resolves the ambiguity, rather than assuming.

> **Status:** the three cells below call the live Anthropic API and have not been executed yet in this notebook — they require `ANTHROPIC_API_KEY` set in the environment (see the API Key Setup section above) plus network access, neither of which is available in this drafting environment. Everything upstream of these calls (schema grounding, the self-healing sanitizer, and the schema guardrail) has been executed and verified independently, so once a key is available these three cells just need `Run All` from here down to complete the notebook.

In [ ]:
# Multi-condition prompt 1: an explicit AND across two independent risk signals
result_1 = generate_and_execute_llm_sql_v3(
    "Show me orders with 2 or more customer support contacts AND a late delivery risk flag",
    conn
)
result_1

In [ ]:
# Multi-condition prompt 2: a business-rule style compound condition
result_2 = generate_and_execute_llm_sql_v3(
    "Find high-value orders over 200 EUR that were flagged with a high risk IP and shipped more than 100km",
    conn
)
result_2

In [ ]:
# Multi-condition prompt 3: deliberately ambiguous -- 'risky' could map to
# risk_label, is_fraud, high_risk_ip, or some combination. Worth seeing how
# the model actually resolves this rather than assuming.
result_3 = generate_and_execute_llm_sql_v3(
    "Show me the riskiest orders",
    conn
)
result_3

### 🧪 Same Three Prompts, via Gemini

Identical questions, run through `generate_and_execute_llm_sql_gemini` instead of the (currently billing-blocked) Anthropic pipeline. Comparing the two providers' SQL for the same prompts — especially the deliberately ambiguous "riskiest orders" case — is itself an interesting mini-audit of how differently grounded LLMs resolve ambiguity.

In [49]:
result_1_gemini = generate_and_execute_llm_sql_gemini(
    "Show me orders with 2 or more customer support contacts AND a late delivery risk flag",
    conn
)
result_1_gemini

💬 User Question: 'Show me orders with 2 or more customer support contacts AND a late delivery risk flag'
------------------------------------------------------------
🤖 Raw LLM Response:
```sql
SELECT
  *
FROM orders
WHERE
  customer_support_contacts >= 2 AND late_delivery_risk = 1;
```
------------------------------------------------------------
🧼 Sanitized SQL (passed guardrail):
SELECT
  *
FROM orders
WHERE
  customer_support_contacts >= 2 AND late_delivery_risk = 1;
------------------------------------------------------------
✅ Pipeline executed successfully.

,order_id,order_date,country,device_type,traffic_source,payment_method,product_category,customer_age_days,previous_orders,avg_order_value_eur,...,shipping_distance_km,delivery_days_estimated,late_delivery_risk,address_mismatch,high_risk_ip,customer_support_contacts,review_score,is_returned,is_fraud,risk_label
0,ORD-2024-007884,06/05/2024,Germany,Desktop,Social Media,Debit Card,Fashion,730,4,35.31,...,1403.5,7,1,0,0,2,2.3,1,0,Return Risk
1,ORD-2023-000048,04/02/2023,Belgium,Mobile,Social Media,Credit Card,Home & Kitchen,143,1,58.52,...,943.2,6,1,0,0,3,1.9,1,0,Return Risk
2,ORD-2024-010459,27/11/2024,Spain,Mobile,Paid Ads,Debit Card,Sports,583,5,18.08,...,2059.5,7,1,0,0,2,3.8,0,0,Normal
3,ORD-2024-007173,06/07/2024,France,Desktop,Direct,Debit Card,Electronics,233,1,84.24,...,1520.5,6,1,0,0,2,3.2,0,0,Normal
4,ORD-2024-010513,31/01/2024,Germany,Desktop,Paid Ads,Gift Card,Fashion,317,2,25.00,...,1035.0,6,1,0,0,3,3.4,0,0,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,ORD-2023-005760,29/04/2023,France,Mobile,Paid Ads,Klarna,Fashion,748,5,37.17,...,1309.0,6,1,0,0,2,1.4,1,0,Return Risk
140,ORD-2023-009987,17/06/2023,Poland,Mobile,Social Media,Gift Card,Sports,489,1,20.40,...,1184.2,4,1,0,0,2,4.1,0,0,Normal
141,ORD-2025-005792,15/12/2025,Netherlands,Mobile,Organic Search,PayPal,Toys,226,1,89.74,...,1153.0,6,1,0,0,2,3.7,0,0,Normal
142,ORD-2023-002732,03/12/2023,Germany,Mobile,Organic Search,Credit Card,Garden,263,0,81.68,...,1112.0,6,1,1,0,2,2.6,1,1,Fraud Risk
143,ORD-2024-007100,06/03/2024,Poland,Tablet,Paid Ads,Credit Card,Toys,142,1,66.02,...,1065.9,6,1,0,0,2,3.2,0,0,Normal

In [50]:
result_2_gemini = generate_and_execute_llm_sql_gemini(
    "Find high-value orders over 200 EUR that were flagged with a high risk IP and shipped more than 100km",
    conn
)
result_2_gemini

💬 User Question: 'Find high-value orders over 200 EUR that were flagged with a high risk IP and shipped more than 100km'
------------------------------------------------------------
🤖 Raw LLM Response:
```sql
SELECT
  *
FROM orders
WHERE
  order_value_eur > 200
  AND high_risk_ip = 1
  AND shipping_distance_km > 100;
```
------------------------------------------------------------
🧼 Sanitized SQL (passed guardrail):
SELECT
  *
FROM orders
WHERE
  order_value_eur > 200
  AND high_risk_ip = 1
  AND shipping_distance_km > 100;
------------------------------------------------------------
✅ Pipeline executed successfully.

,order_id,order_date,country,device_type,traffic_source,payment_method,product_category,customer_age_days,previous_orders,avg_order_value_eur,...,shipping_distance_km,delivery_days_estimated,late_delivery_risk,address_mismatch,high_risk_ip,customer_support_contacts,review_score,is_returned,is_fraud,risk_label
0,ORD-2023-006119,06/06/2023,Germany,Mobile,Email,Klarna,Electronics,546,4,64.94,...,514.2,4,0,0,1,1,4.9,0,0,Normal
1,ORD-2025-005420,02/03/2025,Italy,Tablet,Paid Ads,Credit Card,Home & Kitchen,226,2,69.72,...,225.9,2,0,0,1,0,4.4,0,0,Normal
2,ORD-2025-009744,15/03/2025,Spain,Mobile,Paid Ads,Klarna,Sports,194,2,88.93,...,246.2,2,0,0,1,0,5.0,0,0,Normal
3,ORD-2024-006168,15/04/2024,Netherlands,Mobile,Paid Ads,Debit Card,Home & Kitchen,521,2,111.15,...,856.0,5,0,0,1,0,4.8,0,1,Fraud Risk
4,ORD-2024-011671,05/10/2024,Netherlands,Mobile,Paid Ads,Debit Card,Electronics,641,6,180.96,...,782.6,5,0,0,1,0,4.3,0,0,Normal
5,ORD-2023-007894,29/08/2023,Germany,Desktop,Paid Ads,PayPal,Electronics,131,1,83.63,...,764.0,3,0,0,1,0,4.8,0,0,Normal
6,ORD-2023-007948,12/05/2023,Netherlands,Mobile,Paid Ads,Debit Card,Home & Kitchen,250,0,145.00,...,559.0,4,0,1,1,0,5.0,0,0,Normal
7,ORD-2025-009970,25/05/2025,Germany,Desktop,Paid Ads,Debit Card,Home & Kitchen,167,1,134.21,...,712.9,4,0,0,1,0,4.7,0,1,Fraud Risk
8,ORD-2024-000061,31/03/2024,Belgium,Desktop,Paid Ads,Credit Card,Home & Kitchen,409,0,189.45,...,166.4,4,0,0,1,0,3.8,0,0,Normal
9,ORD-2024-011191,13/12/2024,Belgium,Desktop,Organic Search,Credit Card,Electronics,108,1,114.65,...,367.5,3,0,0,1,1,4.4,0,0,Normal
10,ORD-2025-006234,01/01/2025,Germany,Mobile,Paid Ads,Credit Card,Toys,151,0,176.00,...,396.9,4,0,0,1,0,4.6,0,0,Normal
11,ORD-2025-005714,15/09/2025,Poland,Mobile,Paid Ads,Gift Card,Electronics,507,1,74.85,...,887.2,4,0,0,1,0,5.0,0,1,Fraud Risk
12,ORD-2025-000503,29/08/2025,Netherlands,Mobile,Social Media,PayPal,Toys,316,0,133.60,...,289.2,3,0,0,1,0,3.3,1,0,Return Risk

In [51]:
# Same deliberately ambiguous prompt as the Anthropic version above --
# worth comparing how each provider resolves 'riskiest'.
result_3_gemini = generate_and_execute_llm_sql_gemini(
    "Show me the riskiest orders",
    conn
)
result_3_gemini

💬 User Question: 'Show me the riskiest orders'
------------------------------------------------------------
🤖 Raw LLM Response:
```sql
SELECT
  order_id,
  order_date,
  country,
  device_type,
  traffic_source,
  payment_method,
  product_category,
  customer_age_days,
  previous_orders,
  avg_order_value_eur,
  order_value_eur,
  quantity,

------------------------------------------------------------
⚠️  Guardrail flagged possible hallucinated identifiers: ['sql']
   Refusing to execute. Review the query before running manually.

## 📋 Engineering Decisions Log

A short record of the non-obvious choices made while building this pipeline, and why — the kind of context that's easy to lose once the code is working and the reasoning behind it fades.

**Why ground with the full 23-column schema, not a trimmed version.** The earlier teaching examples in this notebook intentionally use an abbreviated 6-column schema to keep the SQL readable while explaining core concepts. The production pipeline uses the full schema because the multi-condition prompts above depend on columns (`customer_support_contacts`, `late_delivery_risk`, `shipping_distance_km`) that don't exist in the trimmed version — grounding against an incomplete schema would either cause hallucination or simply make those questions unanswerable.

**Why the sanitizer uses non-greedy capture with `re.DOTALL`, not greedy matching.** A greedy `.*` would match from the *first* ` ```sql ` fence all the way to the *last* ` ``` ` in the response, which silently swallows any additional fenced blocks or trailing content in between. Non-greedy `.*?` stops at the nearest closing fence instead, which matches the actual structure of a single SQL block. `re.DOTALL` is required separately because by default `.` doesn't match newlines in Python regex — without it, a multi-line SQL query inside the fence would silently fail to match at all.

**Why the schema guardrail checks identifiers, not full SQL semantics.** A true SQL parser (e.g. validating join correctness, subquery scoping) was out of scope for the actual risk being mitigated: LLMs occasionally invent plausible-sounding column names. A regex-based identifier scan catches that specific failure cheaply, without taking on the complexity of a full parser for a problem that doesn't require one. The cost of that simplicity is the alias false-positive documented above — an accepted tradeoff, not an oversight.

**Why the API key is loaded from an environment variable instead of a config cell.** This notebook is pushed to a public GitHub repo. A key pasted directly into a cell remains in the commit history even after being deleted from the visible notebook state, unless the entire git history is rewritten. An environment variable set outside the notebook avoids that risk entirely.